server:
  port: 5000
spring:
  application:
    name: sun-crowd-project
  thymeleaf:
          prefix: classpath:/templates/
          suffix: .html
  redis:
    host: 127.0.0.1
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
aliyun:
  oss:
    access-key-id: LTAI5tNtz2ZBNUc4DrSdbAiJ
    access-key-secret: N6hmPM1jjYrmxaIMT9hdIfnwwyZbJw
    bucket-domain: http://sun210531.oss-cn-beijing.aliyuncs.com
    bucket-name: sun210531
    end-point: http://oss-cn-beijing.aliyuncs.com